version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/index:/app/data/index

  frontend:
    image: streamlit/streamlit:latest
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
